version: '3.8'

services:
  authapi:
    image: authapi:1.0
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=8000
    networks:
      - social-network
    
  socialapi:
    image: socialapi:1.0
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=8001
    networks:
      - social-network
  
networks:
  social-network:
    driver: bridge
